version: '2' #версия docker-compose
services: #блок описания контейнеров (сервисов)
  graphgl: #название сервиса
    container_name: graphgl #имя контейнера
    image: graphql:latest #название docker-образа, которое будет использоваться как ядро контейнера
    ports: #порты, которые будет использовать контейнер (снаружи:внутри)
      - "18888:8080"